---

- name: Copying keepalived.conf
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
  notify: restart keepalived

- name: Updating net.ipv4.ip_nonlocal_bind parameter
  become: yes
  lineinfile:
    dest: /etc/sysctl.conf
    line: 'net.ipv4.ip_nonlocal_bind=1'

- name: Updating net.ipv4.ip_forward parameter
  become: yes
  lineinfile:
    dest: /etc/sysctl.conf
    line: 'net.ipv4.ip_forward = 1'

- name: Updating sysctl parameters
  become: yes
  shell: sysctl -p

- name: Enable keepalived to be started at boot
  service: name=keepalived enabled=yes state=started
